# This Dockerfile sets up a Python 3.8 environment for a backend application.
# It copies the application code into the container, sets the working directory,
# installs the required dependencies from requirements.txt, and specifies the
# command to run the application using app.py.
FROM PYTHON 3.8

COPY . /app

WORKDIR /app

RUN pip install -r requirements.txt

CMD ["python", "app.py"]

WW